apiVersion: v2
name: monitoring
description: Prometheus and Grafana monitoring stack for Payment Processing System
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "51.2.0"
    repository: https://prometheus-community.github.io/helm-charts 