kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 7d
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 10Gi
  
  grafana:
    persistence:
      size: 5Gi
    
    adminPassword: admin-dev
  
  alertmanager:
    config:
      global:
        resolve_timeout: 1m 